### ISSUE TITLE
Versions  and query regarding gpu

### ISSUE THREAD

**Issue by varghesealex90** [moganesyan/tensorflow_model_deployment#6]
Hello,

1) Can you please specify which tensorflow, keras version were used.
2)" In the same folder, run build_image.sh to build and run a docker image serving the exported model. If you don't have a GPU, remove _gpu on the first line of the docker file. " I dont see gpu in build_image.sh

**Comment by moganesyan** [comment]
1. requirements.txt has the minimum required versions. They were the ones that I used. But should in theory work on the higher up ones as well (except for Tensorflow 2, hence the specified range in the file).
2. You answered your own question. "...  the first line of the docker file ...". The docker file is Dockerfile, not build_image.sh
